#!/usr/bin/env node

require('es6-shim');
var fs = require('fs');
var path = require('path');
var through = require('through');
var split = require('split');
var moment = require('moment');
var level = require('level');
var levelgraph = require('levelgraph');
var sublevel = require('level-sublevel');
var chalk = require('chalk');
var async = require('async');

var path = path.resolve(home(), '.life');
var db = sublevel(level(path));
var entries = db.sublevel('entries', { valueEncoding: 'json' });
var log = db.sublevel('log');
var meta = db.sublevel('meta');
var graph = levelgraph(db.sublevel('graph'));

var dateFormat = 'DD/MM/YY @ hh:mma';

/**
 * Process any args as a new entry
 */
var words = process.argv.slice(2).join(' ');
var entry = words.split(' ').reduce(function (memo, arg, index, args) {
    if (arg && arg.startsWith('@')) {
        var value = args[index + 1];
        if (value) {
            args[index + 1] = null;
        }
        memo.data.push({
            key: arg.slice(1),
            value: value
        });
    } else if (arg &&  arg.startsWith('+')) {
        memo.tags.push(arg.slice(1));
    } else if (arg) {
        memo.annotation = (memo.annotation + ' ' + arg).trim();
    }
    return memo;
}, { data: [], tags: [], annotation: '' });

/**
 * Note to self
 *
 * Queries:
 *     - entries between x & y
 *     - entries with tag
 *     - entries with key
 *     - entry with id
 *
 * Graph:
 *     timestamp -> tagged -> tag
 *     timestamp -> has -> key
 *
 * Entries:
 *     a~timestamp -> entry
 *
 * Log:
 *     k~key~timestamp -> value
 *     t~tag~timestamp -> entry
 *
 * Meta:
 *     stuff
 *
 */

// We got a new entry, add it
if (entry.annotation) {
    return meta.get('id', function (err, id) {
        if (err) {
            if (err.notFound) {
                id = 0;
            } else {
                throw err;
            }
        }

        var timestamp = Date.now();
        id = parseInt(id, 10) + 1;

        entry.id = id;
        entry.timestamp = timestamp;

        var entryOps = [{ key: key('a', timestamp), value: entry, type: 'put' }];
        var logOps = [];
        var graphOps = [];

        entry.tags.forEach(function (tag) {
            logOps.push({ key: key('t', tag, timestamp), value: entry, type: 'put' })
            graphOps.push({ subject: timestamp, predicate: 'tagged', object: tag });
        });
        entry.data.forEach(function (datum) {
            logOps.push({ key: key('k', datum.key, timestamp), value: datum.value, type: 'put' })
            graphOps.push({ subject: timestamp, predicate: 'has', object: datum.key });
        });

        async.parallel([
            entries.batch.bind(entries, entryOps),
            log.batch.bind(log, logOps),
            graph.put.bind(graph, graphOps),
            meta.put.bind(meta, 'id', id)
        ], function (err) {
            if (err) throw err;
            logEntry(entry);
        });
    });
}

// No entry, read out the last 24 hrs
entries
    .createReadStream({ start: key('a', Date.now() - (1000 * 60 * 60 * 24)), end: key('a', '~') })
    .on('data', function (data) {
        logEntry(data.value);
    });

/**
 * Utils
 */

function key() {
    return [].slice.call(arguments).join('~');
}

function unkey(key) {
    var keys = [].slice.call(arguments, 1);
    var segs = key.split('~');
    return segs.reduce(function (memo, seg, index) {
        if (keys[index]) {
            memo[keys[index]] = seg;
        }
        return memo;
    }, {});
}

function home() {
    return process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'];
}

function logEntry(entry) {
    var date = moment(parseInt(entry.timestamp, 10)).format(dateFormat);
    var args = [chalk.grey(date + ' :'), entry.annotation];
    if (entry.tags.length) {
        args.push(
            chalk.blue('+' + entry.tags.join(' +'))
        );
    }
    if (entry.id) {
        args.push(
            chalk.grey('#'+entry.id)
        );
    }
    console.log.apply(console, args);
    var dataBuffer = entry.data.map(function (datum) {
        return chalk.green('@' + datum.key) + ' ' + chalk.yellow(datum.value)
    });
    dataBuffer.length && console.log(' '.repeat(date.length), ' ', dataBuffer.join(', '));
}